stages:
  - install
  - build
  - test
  - deploy

# ---------- LARAVEL ----------
laravel-install:
  stage: install
  image: php:8.4
  before_script:
    - apt-get update
    - apt-get install -y unzip git curl
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
  script:
    - cd api
    - composer install
  artifacts:
    paths:
      - api/vendor/

laravel-test:
  stage: test
  image: php:8.4
  script:
    - cd api
    - php artisan test

# ---------- FRONTEND ----------
frontend-install:
  stage: install
  image: node:24
  script:
    - cd frontend
    - npm install

frontend-build:
  stage: build
  image: node:24
  script:
    - cd frontend
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh
  script:
    - ssh firman@103.103.21.23 "
        cd /var/www/simrs &&
        git pull origin main &&
        cd frontend &&
        npm install &&
        npm run build &&
        cd ../api &&
        composer install --no-dev --optimize-autoloader &&
        php artisan migrate:fresh --seed &&
        php artisan optimize:clear
      "