<?php

namespace Database\Seeders;

use App\Models\Degree;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DegreeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $degrees = [
            ["type" => "prefix", "name" => "Prof."],
            ["type" => "prefix", "name" => "dr."],
            ["type" => "prefix", "name" => "Dr.(H.C.)"],
            ["type" => "prefix", "name" => "drh."],
            ["type" => "prefix", "name" => "drg."],
            ["type" => "prefix", "name" => "Dr. med. dent."],
            ["type" => "prefix", "name" => "Dr. med. vet."],
            ["type" => "prefix", "name" => "Dr. nat med."],
            ["type" => "prefix", "name" => "Dr. rer. med."],
            ["type" => "prefix", "name" => "Dr. rer. medic."],
            ["type" => "prefix", "name" => "Dr. sc. med."],
            ["type" => "prefix", "name" => "Dr. PH"],
            ["type" => "prefix", "name" => "Dr. pharm."],
            ["type" => "prefix", "name" => "Dr. scient. med."],
            ["type" => "prefix", "name" => "Dr. med. dent. et scient. med."],
            ["type" => "prefix", "name" => "Dr. med. univ."],
            ["type" => "prefix", "name" => "Dr. med. univ. et scient. med"],
            ["type" => "prefix", "name" => "dra."],
            ["type" => "prefix", "name" => "drs."],
            ["type" => "prefix", "name" => "Dr. med."],
            ["type" => "prefix", "name" => "Dr."],
            ["type" => "prefix", "name" => "dr. FX.",],
            ["type" => "prefix", "name" => "Dr. dr.",],
            ["type" => "prefix", "name" => "Prof. Dr. med.",],
            ["type" => "prefix", "name" => "Prof. drg.",],
            ["type" => "prefix", "name" => "Dr. drg.",],
            ["type" => "prefix", "name" => "Prof. dr.",],
            ["type" => "prefix", "name" => "Bidan.",],
            ["type" => "prefix", "name" => "Apt.",],
            ["type" => "prefix", "name" => "Ns.",],
            ["type" => "prefix", "name" => "Ft.",],
            ["type" => "prefix", "name" => "Prof. Dr. drg.",],
            ["type" => "prefix", "name" => "Ftr.",],
            ['type' => 'suffix', 'name' => 'M.H.S.A.'],
            ['type' => 'suffix', 'name' => 'FAADV'],
            ['type' => 'suffix', 'name' => 'FINS-DV'],
            ['type' => 'suffix', 'name' => 'Fellowship'],
            ['type' => 'suffix', 'name' => 'Cert.'],
            ['type' => 'suffix', 'name' => 'Cert.Ort.'],
            ['type' => 'suffix', 'name' => 'Postdoctoral Study'],
            ['type' => 'suffix', 'name' => 'C.D.E.'],
            ['type' => 'suffix', 'name' => 'D.P.B.O.'],
            ['type' => 'suffix', 'name' => 'FACSM'],
            ['type' => 'suffix', 'name' => 'IBCLC'],
            ['type' => 'suffix', 'name' => 'FRCS'],
            ['type' => 'suffix', 'name' => 'FRCP'],
            ['type' => 'suffix', 'name' => 'FRCSC'],
            ['type' => 'suffix', 'name' => 'FRCPC'],
            ['type' => 'suffix', 'name' => 'FRCPath'],
            ['type' => 'suffix', 'name' => 'FINASIM'],
            ['type' => 'suffix', 'name' => 'FACG'],
            ['type' => 'suffix', 'name' => 'FCCP'],
            ['type' => 'suffix', 'name' => 'FACOG'],
            ['type' => 'suffix', 'name' => 'FACFAS'],
            ['type' => 'suffix', 'name' => 'FACEP'],
            ['type' => 'suffix', 'name' => 'FACE'],
            ['type' => 'suffix', 'name' => 'FAAFP'],
            ['type' => 'suffix', 'name' => 'FAAEM'],
            ['type' => 'suffix', 'name' => 'FIHA'],
            ['type' => 'suffix', 'name' => 'FICS'],
            ['type' => 'suffix', 'name' => 'FFPHM'],
            ['type' => 'suffix', 'name' => 'FFR'],
            ['type' => 'suffix', 'name' => 'FESC'],
            ['type' => 'suffix', 'name' => 'FACS'],
            ['type' => 'suffix', 'name' => 'FACP'],
            ['type' => 'suffix', 'name' => 'FACC'],
            ['type' => 'suffix', 'name' => 'FAAP'],
            ['type' => 'suffix', 'name' => 'Sp.AH-BAH'],
            ['type' => 'suffix', 'name' => 'Sp.KHLab'],
            ['type' => 'suffix', 'name' => 'Sp.AKAH'],
            ['type' => 'suffix', 'name' => 'Sp.MKVet'],
            ['type' => 'suffix', 'name' => 'Sp.KesMaVet'],
            ['type' => 'suffix', 'name' => 'Sp.Epid'],
            ['type' => 'suffix', 'name' => 'Sp.OR'],
            ['type' => 'suffix', 'name' => 'Sp.GPH'],
            ['type' => 'suffix', 'name' => 'Sp.PH'],
            ['type' => 'suffix', 'name' => 'Sp.NH'],
            ['type' => 'suffix', 'name' => 'Sp.KMVet'],
            ['type' => 'suffix', 'name' => 'Sp.PAVet'],
            ['type' => 'suffix', 'name' => 'Sp.PKVet'],
            ['type' => 'suffix', 'name' => 'Sp.RTD'],
            ['type' => 'suffix', 'name' => 'Sp.KH'],
            ['type' => 'suffix', 'name' => 'Sp.EmerMPKH'],
            ['type' => 'suffix', 'name' => 'Sp.KB-SL'],
            ['type' => 'suffix', 'name' => 'Sp.HKU'],
            ['type' => 'suffix', 'name' => 'Sp.HKRAmp'],
            ['type' => 'suffix', 'name' => 'Sp.HKM'],
            ['type' => 'suffix', 'name' => 'Sp.KLH'],
            ['type' => 'suffix', 'name' => 'Sp.OGH'],
            ['type' => 'suffix', 'name' => 'Sp.I'],
            ['type' => 'suffix', 'name' => 'Sp.HTU'],
            ['type' => 'suffix', 'name' => 'Sp.HTK'],
            ['type' => 'suffix', 'name' => 'Sp.HTB'],
            ['type' => 'suffix', 'name' => 'SP.BH'],
            ['type' => 'suffix', 'name' => 'Sp.ParKVet'],
            ['type' => 'suffix', 'name' => 'Sp.RKG(K)'],
            ['type' => 'suffix', 'name' => 'Sp.FKAnVet'],
            ['type' => 'suffix', 'name' => 'Sp.RKG'],
            ['type' => 'suffix', 'name' => 'Sp.Pros(K)'],
            ['type' => 'suffix', 'name' => 'Sp.Pros'],
            ['type' => 'suffix', 'name' => 'SP.PM(K)'],
            ['type' => 'suffix', 'name' => 'Sp.PM'],
            ['type' => 'suffix', 'name' => 'Sp.Perio(K)'],
            ['type' => 'suffix', 'name' => 'Sp.Perio'],
            ['type' => 'suffix', 'name' => 'Sp.Ort(K)'],
            ['type' => 'suffix', 'name' => 'Sp.Ort'],
            ['type' => 'suffix', 'name' => 'Sp.KGA(K)'],
            ['type' => 'suffix', 'name' => 'Sp.KGA'],
            ['type' => 'suffix', 'name' => 'Sp.KG'],
            ['type' => 'suffix', 'name' => 'Sp.KG(K)'],
            ['type' => 'suffix', 'name' => 'Sp.BM(K)'],
            ['type' => 'suffix', 'name' => 'Sp.BM'],
            ['type' => 'suffix', 'name' => 'Sp.KL'],
            ['type' => 'suffix', 'name' => 'Sp.Ger'],
            ['type' => 'suffix', 'name' => 'Sp.U(K)'],
            ['type' => 'suffix', 'name' => 'Sp.U'],
            ['type' => 'suffix', 'name' => 'Sp.THT-KL(K)'],
            ['type' => 'suffix', 'name' => 'Sp.THT-KL'],
            ['type' => 'suffix', 'name' => 'Sp.S(K)'],
            ['type' => 'suffix', 'name' => 'Sp.S'],
            ['type' => 'suffix', 'name' => 'Sp.S-KIC'],
            ['type' => 'suffix', 'name' => 'Sp.Rad(K)'],
            ['type' => 'suffix', 'name' => 'Sp.Rad'],
            ['type' => 'suffix', 'name' => 'Sp.PK(K)'],
            ['type' => 'suffix', 'name' => 'Sp.PK'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KPTI'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KR'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KP'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KPsi'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KEMD'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KH'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KGer'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KGEH'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KAI'],
            ['type' => 'suffix', 'name' => 'Sp.PD_KHOM'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KKV'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KGH'],
            ['type' => 'suffix', 'name' => 'Sp.PD'],
            ['type' => 'suffix', 'name' => 'Sp.PA(K)'],
            ['type' => 'suffix', 'name' => 'Sp.P'],
            ['type' => 'suffix', 'name' => 'Sp.Onk.Rad'],
            ['type' => 'suffix', 'name' => 'Sp.Ok'],
            ['type' => 'suffix', 'name' => 'Sp.OG(K)'],
            ['type' => 'suffix', 'name' => 'Sp.OG-KFM'],
            ['type' => 'suffix', 'name' => 'Sp.OF-KFER'],
            ['type' => 'suffix', 'name' => 'Sp.OG(K)Onk'],
            ['type' => 'suffix', 'name' => 'Sp.OG'],
            ['type' => 'suffix', 'name' => 'Sp.MK(K)'],
            ['type' => 'suffix', 'name' => 'Sp.MK'],
            ['type' => 'suffix', 'name' => 'Sp.M(K)'],
            ['type' => 'suffix', 'name' => 'Sp.M'],
            ['type' => 'suffix', 'name' => 'Sp.KO'],
            ['type' => 'suffix', 'name' => 'Sp.KN'],
            ['type' => 'suffix', 'name' => 'Sp.EM'],
            ['type' => 'suffix', 'name' => 'Sp.KK(K)'],
            ['type' => 'suffix', 'name' => 'Sp.KK'],
            ['type' => 'suffix', 'name' => 'Sp.KP'],
            ['type' => 'suffix', 'name' => 'Sp.KJ(K)'],
            ['type' => 'suffix', 'name' => 'Sp.KJ'],
            ['type' => 'suffix', 'name' => 'Sp.KFR(K)'],
            ['type' => 'suffix', 'name' => 'Sp.KFR'],
            ['type' => 'suffix', 'name' => 'Sp.JP(K)'],
            ['type' => 'suffix', 'name' => 'Sp.JP'],
            ['type' => 'suffix', 'name' => 'Sp.GK'],
            ['type' => 'suffix', 'name' => 'Sp.FK(K)'],
            ['type' => 'suffix', 'name' => 'Sp.FK'],
            ['type' => 'suffix', 'name' => 'Sp.F(K)'],
            ['type' => 'suffix', 'name' => 'Sp.F'],
            ['type' => 'suffix', 'name' => 'Sp.BTKV(K)'],
            ['type' => 'suffix', 'name' => 'Sp.BTKV'],
            ['type' => 'suffix', 'name' => 'Sp.OT(K)-Spine'],
            ['type' => 'suffix', 'name' => 'Sp.OT(K)'],
            ['type' => 'suffix', 'name' => 'Sp.OT'],
            ['type' => 'suffix', 'name' => 'Sp.BS(K)'],
            ['type' => 'suffix', 'name' => 'Sp.BS'],
            ['type' => 'suffix', 'name' => 'Sp.BP-RE(K)'],
            ['type' => 'suffix', 'name' => 'Sp.BP-RE'],
            ['type' => 'suffix', 'name' => 'Sp.BA(K)'],
            ['type' => 'suffix', 'name' => 'Sp.BA'],
            ['type' => 'suffix', 'name' => 'Sp.B(K)Trauma'],
            ['type' => 'suffix', 'name' => 'Sp.B-KKL'],
            ['type' => 'suffix', 'name' => 'Sp.B-KV'],
            ['type' => 'suffix', 'name' => 'Sp.B(K)Onk'],
            ['type' => 'suffix', 'name' => 'Sp.B-KBD'],
            ['type' => 'suffix', 'name' => 'Sp.B'],
            ['type' => 'suffix', 'name' => 'Sp.Ak'],
            ['type' => 'suffix', 'name' => 'Sp.And'],
            ['type' => 'suffix', 'name' => 'Sp.An-KAO'],
            ['type' => 'suffix', 'name' => 'Sp.An-KAP'],
            ['type' => 'suffix', 'name' => 'Sp.An-KNA'],
            ['type' => 'suffix', 'name' => 'Sp.An-KAR'],
            ['type' => 'suffix', 'name' => 'Sp.An-KMN'],
            ['type' => 'suffix', 'name' => 'Sp.An-KAKV'],
            ['type' => 'suffix', 'name' => 'Sp.An-KIC'],
            ['type' => 'suffix', 'name' => 'Sp.An'],
            ['type' => 'suffix', 'name' => 'Sp.A(K)'],
            ['type' => 'suffix', 'name' => 'Sp.A'],
            ['type' => 'suffix', 'name' => 'Certification In Oral Chirurgie'],
            ['type' => 'suffix', 'name' => 'C.Ht.'],
            ['type' => 'suffix', 'name' => 'D.P.H.'],
            ['type' => 'suffix', 'name' => 'D.S.N.'],
            ['type' => 'suffix', 'name' => 'Pharmn.D.'],
            ['type' => 'suffix', 'name' => 'D.V.M.'],
            ['type' => 'suffix', 'name' => 'D.Sc.P.T.'],
            ['type' => 'suffix', 'name' => 'D.P.T.'],
            ['type' => 'suffix', 'name' => 'O.D.'],
            ['type' => 'suffix', 'name' => 'D.O.'],
            ['type' => 'suffix', 'name' => 'Au.D.'],
            ['type' => 'suffix', 'name' => 'D.D.S.'],
            ['type' => 'suffix', 'name' => 'D.C.'],
            ['type' => 'suffix', 'name' => 'D.P.M'],
            ['type' => 'suffix', 'name' => 'D.M.D'],
            ['type' => 'suffix', 'name' => 'M.D.'],
            ['type' => 'suffix', 'name' => 'Sc.D.'],
            ['type' => 'suffix', 'name' => 'D.Sc.'],
            ['type' => 'suffix', 'name' => 'Ph.D.'],
            ['type' => 'suffix', 'name' => 'MMed(Paed)'],
            ['type' => 'suffix', 'name' => 'M.I.M.H'],
            ['type' => 'suffix', 'name' => 'Diplom Arbeitsmedizin'],
            ['type' => 'suffix', 'name' => 'DTHMP'],
            ['type' => 'suffix', 'name' => 'M.Kes.,Sert.Ort.'],
            ['type' => 'suffix', 'name' => 'M.Farm.Klin.'],
            ['type' => 'suffix', 'name' => 'M.Farm.'],
            ['type' => 'suffix', 'name' => 'M.Epid.'],
            ['type' => 'suffix', 'name' => 'M.Ked.Trop.'],
            ['type' => 'suffix', 'name' => 'M.K.K.K.'],
            ['type' => 'suffix', 'name' => 'M.K.M.'],
            ['type' => 'suffix', 'name' => 'M.Si.'],
            ['type' => 'suffix', 'name' => 'M.Psi.'],
            ['type' => 'suffix', 'name' => 'M.H.Kes.'],
            ['type' => 'suffix', 'name' => 'M.M.Kes'],
            ['type' => 'suffix', 'name' => 'M.K.K.'],
            ['type' => 'suffix', 'name' => 'M.A.R.S.'],
            ['type' => 'suffix', 'name' => 'M.M.R.S.'],
            ['type' => 'suffix', 'name' => 'M.Kesja.'],
            ['type' => 'suffix', 'name' => 'M.Si.Med.'],
            ['type' => 'suffix', 'name' => 'M.Biomed.'],
            ['type' => 'suffix', 'name' => 'M.Gizi'],
            ['type' => 'suffix', 'name' => 'M.Gz.'],
            ['type' => 'suffix', 'name' => 'M.Pd.Ked.'],
            ['type' => 'suffix', 'name' => 'M.K.H.'],
            ['type' => 'suffix', 'name' => 'M.K.G.'],
            ['type' => 'suffix', 'name' => 'M.Ked.'],
            ['type' => 'suffix', 'name' => 'M.Kes.'],
            ['type' => 'suffix', 'name' => 'M.S.'],
            ['type' => 'suffix', 'name' => 'M.H.S.'],
            ['type' => 'suffix', 'name' => 'M.H.A.'],
            ['type' => 'suffix', 'name' => 'M.Sc.'],
            ['type' => 'suffix', 'name' => 'M.Phil.'],
            ['type' => 'suffix', 'name' => 'M.P.H.'],
            ['type' => 'suffix', 'name' => 'BMSc'],
            ['type' => 'suffix', 'name' => 'BSCi(Med)'],
            ['type' => 'suffix', 'name' => 'BMedSci'],
            ['type' => 'suffix', 'name' => 'M.B.Ch.B'],
            ['type' => 'suffix', 'name' => 'S.Farm., Apt.'],
            ['type' => 'suffix', 'name' => 'S.Farm.'],
            ['type' => 'suffix', 'name' => 'S.Si., Apt.'],
            ['type' => 'suffix', 'name' => 'S.Si.'],
            ['type' => 'suffix', 'name' => 'S.Psi.'],
            ['type' => 'suffix', 'name' => 'S.Gz.'],
            ['type' => 'suffix', 'name' => 'S.K.M.'],
            ['type' => 'suffix', 'name' => 'S.K.G.'],
            ['type' => 'suffix', 'name' => 'S.K.H.'],
            ['type' => 'suffix', 'name' => 'S.Ked.'],
            ['type' => 'suffix', 'name' => 'D.C.P.'],
            ['type' => 'suffix', 'name' => 'D.A.P.&E.'],
            ['type' => 'suffix', 'name' => 'D.M.M.'],
            ['type' => 'suffix', 'name' => 'D.T.M.&H.'],
            ['type' => 'suffix', 'name' => 'D.F.M.'],
            ['type' => 'suffix', 'name' => 'FMFM'],
            ['type' => 'suffix', 'name' => 'FISA'],
            ['type' => 'suffix', 'name' => 'FINACS'],
            ['type' => 'suffix', 'name' => 'FSCAI'],
            ['type' => 'suffix', 'name' => 'FAPSIC'],
            ['type' => 'suffix', 'name' => 'Amd.OT'],
            ['type' => 'suffix', 'name' => 'M.Med(Ped)'],
            ['type' => 'suffix', 'name' => 'Fellowship n Pediatric Pulmonology'],
            ['type' => 'suffix', 'name' => 'D.P.P.S'],
            ['type' => 'suffix', 'name' => 'Amd.FT'],
            ['type' => 'suffix', 'name' => 'M.Sc.Periodontology'],
            ['type' => 'suffix', 'name' => 'M.D.S'],
            ['type' => 'suffix', 'name' => 'M.M.R'],
            ['type' => 'suffix', 'name' => 'Diploma IV'],
            ['type' => 'suffix', 'name' => 'Sp.PD-KIC'],
            ['type' => 'suffix', 'name' => 'MPH&TM'],
            ['type' => 'suffix', 'name' => 'FINS'],
            ['type' => 'suffix', 'name' => 'S.Ft'],
            ['type' => 'suffix', 'name' => 'L.Ac.'],
            ['type' => 'suffix', 'name' => 'Dipl.AAAM'],
            ['type' => 'suffix', 'name' => 'P.K.K.'],
            ['type' => 'suffix', 'name' => 'M.M.'],
            ['type' => 'suffix', 'name' => 'M.Biomed (AAM)'],
            ['type' => 'suffix', 'name' => 'MWALS'],
            ['type' => 'suffix', 'name' => 'Sp.DV'],
            ['type' => 'suffix', 'name' => 'DK'],
            ['type' => 'suffix', 'name' => 'MKK/MFM'],
            ['type' => 'suffix', 'name' => 'SpFM'],
            ['type' => 'suffix', 'name' => 'Sp.P(K)'],
            ['type' => 'suffix', 'name' => 'M. Sc'],
            ['type' => 'suffix', 'name' => 'S.E'],
            ['type' => 'suffix', 'name' => 'S.ST'],
            ['type' => 'suffix', 'name' => 'Amd. Kes'],
            ['type' => 'suffix', 'name' => 'SKM'],
            ['type' => 'suffix', 'name' => 'Amd. Keb'],
            ['type' => 'suffix', 'name' => 'S. Kep'],
            ['type' => 'suffix', 'name' => 'M.Si'],
            ['type' => 'suffix', 'name' => 'MARS'],
            ['type' => 'suffix', 'name' => 'Amd. Farm'],
            ['type' => 'suffix', 'name' => 'Amd. Kep'],
            ['type' => 'suffix', 'name' => 'Amd. AK'],
            ['type' => 'suffix', 'name' => 'SpKO'],
            ['type' => 'suffix', 'name' => 'SpKFR'],
            ['type' => 'suffix', 'name' => 'AIFO-K'],
            ['type' => 'suffix', 'name' => 'Sp.KKLP'],
            ['type' => 'suffix', 'name' => 'Sp.N'],
            ['type' => 'suffix', 'name' => 'S.Tr.Kes'],
            ['type' => 'suffix', 'name' => 'Sp.N (K)'],
            ['type' => 'suffix', 'name' => 'MH'],
        ];

        foreach ($degrees as $degree) {
            Degree::create($degree);
        }
    }
}
