/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailVerifyRouteImport } from './routes/email/verify'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedUpgradeIndexRouteImport } from './routes/_protected/upgrade/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedPharmacyIndexRouteImport } from './routes/_protected/pharmacy/index'
import { Route as ProtectedOutpatientIndexRouteImport } from './routes/_protected/outpatient/index'
import { Route as ProtectedInpatientIndexRouteImport } from './routes/_protected/inpatient/index'
import { Route as ProtectedFacilitiesIndexRouteImport } from './routes/_protected/facilities/index'
import { Route as ProtectedElectronicMedicalRecordIndexRouteImport } from './routes/_protected/electronic-medical-record/index'
import { Route as ProtectedAppointmentsIndexRouteImport } from './routes/_protected/appointments/index'
import { Route as ProtectedAccountingIndexRouteImport } from './routes/_protected/accounting/index'
import { Route as ProtectedInpatientCreateRouteImport } from './routes/_protected/inpatient/create'
import { Route as ProtectedInpatientIdRouteImport } from './routes/_protected/inpatient/$id'
import { Route as ProtectedAppointmentsCreateRouteImport } from './routes/_protected/appointments/create'
import { Route as ProtectedAppointmentsIdRouteImport } from './routes/_protected/appointments/$id'
import { Route as ProtectedSettingsUsersManagementIndexRouteImport } from './routes/_protected/settings/users-management/index'
import { Route as ProtectedSettingsReferencesIndexRouteImport } from './routes/_protected/settings/references/index'
import { Route as ProtectedSettingsPatientsIndexRouteImport } from './routes/_protected/settings/patients/index'
import { Route as ProtectedSettingsMedicineManagementIndexRouteImport } from './routes/_protected/settings/medicine-management/index'
import { Route as ProtectedOutpatientVisitIndexRouteImport } from './routes/_protected/outpatient/visit/index'
import { Route as ProtectedMasterModuleIndexRouteImport } from './routes/_protected/master/module/index'
import { Route as ProtectedFacilitiesInpatientIndexRouteImport } from './routes/_protected/facilities/inpatient/index'
import { Route as ProtectedBillingOutpatientIndexRouteImport } from './routes/_protected/billing/outpatient/index'
import { Route as ProtectedBillingInpatientIndexRouteImport } from './routes/_protected/billing/inpatient/index'
import { Route as ProtectedSettingsPatientsCreateRouteImport } from './routes/_protected/settings/patients/create'
import { Route as ProtectedSettingsPatientsIdRouteImport } from './routes/_protected/settings/patients/$id'
import { Route as ProtectedPharmacyWarehouseCreateRouteImport } from './routes/_protected/pharmacy/warehouse/create'
import { Route as ProtectedPharmacyWarehouseIdRouteImport } from './routes/_protected/pharmacy/warehouse/$id'
import { Route as ProtectedPharmacyMedicineCreateRouteImport } from './routes/_protected/pharmacy/medicine/create'
import { Route as ProtectedPharmacyMedicineIdRouteImport } from './routes/_protected/pharmacy/medicine/$id'
import { Route as ProtectedOutpatientVisitCreateRouteImport } from './routes/_protected/outpatient/visit/create'
import { Route as ProtectedOutpatientVisitIdRouteImport } from './routes/_protected/outpatient/visit/$id'
import { Route as ProtectedOutpatientDiagnoseIdRouteImport } from './routes/_protected/outpatient/diagnose/$id'
import { Route as ProtectedSettingsUsersManagementRolesIndexRouteImport } from './routes/_protected/settings/users-management/roles/index'
import { Route as ProtectedSettingsUsersManagementUsersCreateRouteImport } from './routes/_protected/settings/users-management/users/create'
import { Route as ProtectedSettingsPatientsDetailsIdRouteImport } from './routes/_protected/settings/patients/details.$id'
import { Route as ProtectedSettingsMedicineManagementWarehouseCreateRouteImport } from './routes/_protected/settings/medicine-management/warehouse/create'
import { Route as ProtectedSettingsMedicineManagementWarehouseIdRouteImport } from './routes/_protected/settings/medicine-management/warehouse/$id'
import { Route as ProtectedSettingsMedicineManagementMedicineCreateRouteImport } from './routes/_protected/settings/medicine-management/medicine/create'
import { Route as ProtectedSettingsMedicineManagementMedicineIdRouteImport } from './routes/_protected/settings/medicine-management/medicine/$id'
import { Route as ProtectedPharmacyMedicineStocksIdRouteImport } from './routes/_protected/pharmacy/medicine/stocks/$id'
import { Route as ProtectedOutpatientVisitEditIdRouteImport } from './routes/_protected/outpatient/visit/edit/$id'
import { Route as ProtectedSettingsUsersManagementUsersIdIndexRouteImport } from './routes/_protected/settings/users-management/users/$id/index'
import { Route as ProtectedSettingsUsersManagementUsersIdDetailRouteImport } from './routes/_protected/settings/users-management/users/$id/detail'
import { Route as ProtectedSettingsMedicineManagementMedicineStocksIdRouteImport } from './routes/_protected/settings/medicine-management/medicine/stocks/$id'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifyRoute = EmailVerifyRouteImport.update({
  id: '/email/verify',
  path: '/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUpgradeIndexRoute = ProtectedUpgradeIndexRouteImport.update({
  id: '/upgrade/',
  path: '/upgrade/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPharmacyIndexRoute = ProtectedPharmacyIndexRouteImport.update({
  id: '/pharmacy/',
  path: '/pharmacy/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOutpatientIndexRoute =
  ProtectedOutpatientIndexRouteImport.update({
    id: '/outpatient/',
    path: '/outpatient/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInpatientIndexRoute = ProtectedInpatientIndexRouteImport.update({
  id: '/inpatient/',
  path: '/inpatient/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFacilitiesIndexRoute =
  ProtectedFacilitiesIndexRouteImport.update({
    id: '/facilities/',
    path: '/facilities/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedElectronicMedicalRecordIndexRoute =
  ProtectedElectronicMedicalRecordIndexRouteImport.update({
    id: '/electronic-medical-record/',
    path: '/electronic-medical-record/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAppointmentsIndexRoute =
  ProtectedAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAccountingIndexRoute =
  ProtectedAccountingIndexRouteImport.update({
    id: '/accounting/',
    path: '/accounting/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInpatientCreateRoute =
  ProtectedInpatientCreateRouteImport.update({
    id: '/inpatient/create',
    path: '/inpatient/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInpatientIdRoute = ProtectedInpatientIdRouteImport.update({
  id: '/inpatient/$id',
  path: '/inpatient/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppointmentsCreateRoute =
  ProtectedAppointmentsCreateRouteImport.update({
    id: '/appointments/create',
    path: '/appointments/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAppointmentsIdRoute = ProtectedAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsUsersManagementIndexRoute =
  ProtectedSettingsUsersManagementIndexRouteImport.update({
    id: '/settings/users-management/',
    path: '/settings/users-management/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsReferencesIndexRoute =
  ProtectedSettingsReferencesIndexRouteImport.update({
    id: '/settings/references/',
    path: '/settings/references/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsPatientsIndexRoute =
  ProtectedSettingsPatientsIndexRouteImport.update({
    id: '/settings/patients/',
    path: '/settings/patients/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsMedicineManagementIndexRoute =
  ProtectedSettingsMedicineManagementIndexRouteImport.update({
    id: '/settings/medicine-management/',
    path: '/settings/medicine-management/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOutpatientVisitIndexRoute =
  ProtectedOutpatientVisitIndexRouteImport.update({
    id: '/outpatient/visit/',
    path: '/outpatient/visit/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMasterModuleIndexRoute =
  ProtectedMasterModuleIndexRouteImport.update({
    id: '/master/module/',
    path: '/master/module/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedFacilitiesInpatientIndexRoute =
  ProtectedFacilitiesInpatientIndexRouteImport.update({
    id: '/facilities/inpatient/',
    path: '/facilities/inpatient/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedBillingOutpatientIndexRoute =
  ProtectedBillingOutpatientIndexRouteImport.update({
    id: '/billing/outpatient/',
    path: '/billing/outpatient/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedBillingInpatientIndexRoute =
  ProtectedBillingInpatientIndexRouteImport.update({
    id: '/billing/inpatient/',
    path: '/billing/inpatient/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsPatientsCreateRoute =
  ProtectedSettingsPatientsCreateRouteImport.update({
    id: '/settings/patients/create',
    path: '/settings/patients/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsPatientsIdRoute =
  ProtectedSettingsPatientsIdRouteImport.update({
    id: '/settings/patients/$id',
    path: '/settings/patients/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPharmacyWarehouseCreateRoute =
  ProtectedPharmacyWarehouseCreateRouteImport.update({
    id: '/pharmacy/warehouse/create',
    path: '/pharmacy/warehouse/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPharmacyWarehouseIdRoute =
  ProtectedPharmacyWarehouseIdRouteImport.update({
    id: '/pharmacy/warehouse/$id',
    path: '/pharmacy/warehouse/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPharmacyMedicineCreateRoute =
  ProtectedPharmacyMedicineCreateRouteImport.update({
    id: '/pharmacy/medicine/create',
    path: '/pharmacy/medicine/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPharmacyMedicineIdRoute =
  ProtectedPharmacyMedicineIdRouteImport.update({
    id: '/pharmacy/medicine/$id',
    path: '/pharmacy/medicine/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOutpatientVisitCreateRoute =
  ProtectedOutpatientVisitCreateRouteImport.update({
    id: '/outpatient/visit/create',
    path: '/outpatient/visit/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOutpatientVisitIdRoute =
  ProtectedOutpatientVisitIdRouteImport.update({
    id: '/outpatient/visit/$id',
    path: '/outpatient/visit/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOutpatientDiagnoseIdRoute =
  ProtectedOutpatientDiagnoseIdRouteImport.update({
    id: '/outpatient/diagnose/$id',
    path: '/outpatient/diagnose/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsUsersManagementRolesIndexRoute =
  ProtectedSettingsUsersManagementRolesIndexRouteImport.update({
    id: '/settings/users-management/roles/',
    path: '/settings/users-management/roles/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsUsersManagementUsersCreateRoute =
  ProtectedSettingsUsersManagementUsersCreateRouteImport.update({
    id: '/settings/users-management/users/create',
    path: '/settings/users-management/users/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsPatientsDetailsIdRoute =
  ProtectedSettingsPatientsDetailsIdRouteImport.update({
    id: '/settings/patients/details/$id',
    path: '/settings/patients/details/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsMedicineManagementWarehouseCreateRoute =
  ProtectedSettingsMedicineManagementWarehouseCreateRouteImport.update({
    id: '/settings/medicine-management/warehouse/create',
    path: '/settings/medicine-management/warehouse/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsMedicineManagementWarehouseIdRoute =
  ProtectedSettingsMedicineManagementWarehouseIdRouteImport.update({
    id: '/settings/medicine-management/warehouse/$id',
    path: '/settings/medicine-management/warehouse/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsMedicineManagementMedicineCreateRoute =
  ProtectedSettingsMedicineManagementMedicineCreateRouteImport.update({
    id: '/settings/medicine-management/medicine/create',
    path: '/settings/medicine-management/medicine/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsMedicineManagementMedicineIdRoute =
  ProtectedSettingsMedicineManagementMedicineIdRouteImport.update({
    id: '/settings/medicine-management/medicine/$id',
    path: '/settings/medicine-management/medicine/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPharmacyMedicineStocksIdRoute =
  ProtectedPharmacyMedicineStocksIdRouteImport.update({
    id: '/pharmacy/medicine/stocks/$id',
    path: '/pharmacy/medicine/stocks/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOutpatientVisitEditIdRoute =
  ProtectedOutpatientVisitEditIdRouteImport.update({
    id: '/outpatient/visit/edit/$id',
    path: '/outpatient/visit/edit/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsUsersManagementUsersIdIndexRoute =
  ProtectedSettingsUsersManagementUsersIdIndexRouteImport.update({
    id: '/settings/users-management/users/$id/',
    path: '/settings/users-management/users/$id/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsUsersManagementUsersIdDetailRoute =
  ProtectedSettingsUsersManagementUsersIdDetailRouteImport.update({
    id: '/settings/users-management/users/$id/detail',
    path: '/settings/users-management/users/$id/detail',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsMedicineManagementMedicineStocksIdRoute =
  ProtectedSettingsMedicineManagementMedicineStocksIdRouteImport.update({
    id: '/settings/medicine-management/medicine/stocks/$id',
    path: '/settings/medicine-management/medicine/stocks/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/email/verify': typeof EmailVerifyRoute
  '/appointments/$id': typeof ProtectedAppointmentsIdRoute
  '/appointments/create': typeof ProtectedAppointmentsCreateRoute
  '/inpatient/$id': typeof ProtectedInpatientIdRoute
  '/inpatient/create': typeof ProtectedInpatientCreateRoute
  '/accounting/': typeof ProtectedAccountingIndexRoute
  '/appointments/': typeof ProtectedAppointmentsIndexRoute
  '/electronic-medical-record/': typeof ProtectedElectronicMedicalRecordIndexRoute
  '/facilities/': typeof ProtectedFacilitiesIndexRoute
  '/inpatient/': typeof ProtectedInpatientIndexRoute
  '/outpatient/': typeof ProtectedOutpatientIndexRoute
  '/pharmacy/': typeof ProtectedPharmacyIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/upgrade/': typeof ProtectedUpgradeIndexRoute
  '/outpatient/diagnose/$id': typeof ProtectedOutpatientDiagnoseIdRoute
  '/outpatient/visit/$id': typeof ProtectedOutpatientVisitIdRoute
  '/outpatient/visit/create': typeof ProtectedOutpatientVisitCreateRoute
  '/pharmacy/medicine/$id': typeof ProtectedPharmacyMedicineIdRoute
  '/pharmacy/medicine/create': typeof ProtectedPharmacyMedicineCreateRoute
  '/pharmacy/warehouse/$id': typeof ProtectedPharmacyWarehouseIdRoute
  '/pharmacy/warehouse/create': typeof ProtectedPharmacyWarehouseCreateRoute
  '/settings/patients/$id': typeof ProtectedSettingsPatientsIdRoute
  '/settings/patients/create': typeof ProtectedSettingsPatientsCreateRoute
  '/billing/inpatient/': typeof ProtectedBillingInpatientIndexRoute
  '/billing/outpatient/': typeof ProtectedBillingOutpatientIndexRoute
  '/facilities/inpatient/': typeof ProtectedFacilitiesInpatientIndexRoute
  '/master/module/': typeof ProtectedMasterModuleIndexRoute
  '/outpatient/visit/': typeof ProtectedOutpatientVisitIndexRoute
  '/settings/medicine-management/': typeof ProtectedSettingsMedicineManagementIndexRoute
  '/settings/patients/': typeof ProtectedSettingsPatientsIndexRoute
  '/settings/references/': typeof ProtectedSettingsReferencesIndexRoute
  '/settings/users-management/': typeof ProtectedSettingsUsersManagementIndexRoute
  '/outpatient/visit/edit/$id': typeof ProtectedOutpatientVisitEditIdRoute
  '/pharmacy/medicine/stocks/$id': typeof ProtectedPharmacyMedicineStocksIdRoute
  '/settings/medicine-management/medicine/$id': typeof ProtectedSettingsMedicineManagementMedicineIdRoute
  '/settings/medicine-management/medicine/create': typeof ProtectedSettingsMedicineManagementMedicineCreateRoute
  '/settings/medicine-management/warehouse/$id': typeof ProtectedSettingsMedicineManagementWarehouseIdRoute
  '/settings/medicine-management/warehouse/create': typeof ProtectedSettingsMedicineManagementWarehouseCreateRoute
  '/settings/patients/details/$id': typeof ProtectedSettingsPatientsDetailsIdRoute
  '/settings/users-management/users/create': typeof ProtectedSettingsUsersManagementUsersCreateRoute
  '/settings/users-management/roles/': typeof ProtectedSettingsUsersManagementRolesIndexRoute
  '/settings/medicine-management/medicine/stocks/$id': typeof ProtectedSettingsMedicineManagementMedicineStocksIdRoute
  '/settings/users-management/users/$id/detail': typeof ProtectedSettingsUsersManagementUsersIdDetailRoute
  '/settings/users-management/users/$id/': typeof ProtectedSettingsUsersManagementUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/email/verify': typeof EmailVerifyRoute
  '/appointments/$id': typeof ProtectedAppointmentsIdRoute
  '/appointments/create': typeof ProtectedAppointmentsCreateRoute
  '/inpatient/$id': typeof ProtectedInpatientIdRoute
  '/inpatient/create': typeof ProtectedInpatientCreateRoute
  '/accounting': typeof ProtectedAccountingIndexRoute
  '/appointments': typeof ProtectedAppointmentsIndexRoute
  '/electronic-medical-record': typeof ProtectedElectronicMedicalRecordIndexRoute
  '/facilities': typeof ProtectedFacilitiesIndexRoute
  '/inpatient': typeof ProtectedInpatientIndexRoute
  '/outpatient': typeof ProtectedOutpatientIndexRoute
  '/pharmacy': typeof ProtectedPharmacyIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/upgrade': typeof ProtectedUpgradeIndexRoute
  '/outpatient/diagnose/$id': typeof ProtectedOutpatientDiagnoseIdRoute
  '/outpatient/visit/$id': typeof ProtectedOutpatientVisitIdRoute
  '/outpatient/visit/create': typeof ProtectedOutpatientVisitCreateRoute
  '/pharmacy/medicine/$id': typeof ProtectedPharmacyMedicineIdRoute
  '/pharmacy/medicine/create': typeof ProtectedPharmacyMedicineCreateRoute
  '/pharmacy/warehouse/$id': typeof ProtectedPharmacyWarehouseIdRoute
  '/pharmacy/warehouse/create': typeof ProtectedPharmacyWarehouseCreateRoute
  '/settings/patients/$id': typeof ProtectedSettingsPatientsIdRoute
  '/settings/patients/create': typeof ProtectedSettingsPatientsCreateRoute
  '/billing/inpatient': typeof ProtectedBillingInpatientIndexRoute
  '/billing/outpatient': typeof ProtectedBillingOutpatientIndexRoute
  '/facilities/inpatient': typeof ProtectedFacilitiesInpatientIndexRoute
  '/master/module': typeof ProtectedMasterModuleIndexRoute
  '/outpatient/visit': typeof ProtectedOutpatientVisitIndexRoute
  '/settings/medicine-management': typeof ProtectedSettingsMedicineManagementIndexRoute
  '/settings/patients': typeof ProtectedSettingsPatientsIndexRoute
  '/settings/references': typeof ProtectedSettingsReferencesIndexRoute
  '/settings/users-management': typeof ProtectedSettingsUsersManagementIndexRoute
  '/outpatient/visit/edit/$id': typeof ProtectedOutpatientVisitEditIdRoute
  '/pharmacy/medicine/stocks/$id': typeof ProtectedPharmacyMedicineStocksIdRoute
  '/settings/medicine-management/medicine/$id': typeof ProtectedSettingsMedicineManagementMedicineIdRoute
  '/settings/medicine-management/medicine/create': typeof ProtectedSettingsMedicineManagementMedicineCreateRoute
  '/settings/medicine-management/warehouse/$id': typeof ProtectedSettingsMedicineManagementWarehouseIdRoute
  '/settings/medicine-management/warehouse/create': typeof ProtectedSettingsMedicineManagementWarehouseCreateRoute
  '/settings/patients/details/$id': typeof ProtectedSettingsPatientsDetailsIdRoute
  '/settings/users-management/users/create': typeof ProtectedSettingsUsersManagementUsersCreateRoute
  '/settings/users-management/roles': typeof ProtectedSettingsUsersManagementRolesIndexRoute
  '/settings/medicine-management/medicine/stocks/$id': typeof ProtectedSettingsMedicineManagementMedicineStocksIdRoute
  '/settings/users-management/users/$id/detail': typeof ProtectedSettingsUsersManagementUsersIdDetailRoute
  '/settings/users-management/users/$id': typeof ProtectedSettingsUsersManagementUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/email/verify': typeof EmailVerifyRoute
  '/_protected/appointments/$id': typeof ProtectedAppointmentsIdRoute
  '/_protected/appointments/create': typeof ProtectedAppointmentsCreateRoute
  '/_protected/inpatient/$id': typeof ProtectedInpatientIdRoute
  '/_protected/inpatient/create': typeof ProtectedInpatientCreateRoute
  '/_protected/accounting/': typeof ProtectedAccountingIndexRoute
  '/_protected/appointments/': typeof ProtectedAppointmentsIndexRoute
  '/_protected/electronic-medical-record/': typeof ProtectedElectronicMedicalRecordIndexRoute
  '/_protected/facilities/': typeof ProtectedFacilitiesIndexRoute
  '/_protected/inpatient/': typeof ProtectedInpatientIndexRoute
  '/_protected/outpatient/': typeof ProtectedOutpatientIndexRoute
  '/_protected/pharmacy/': typeof ProtectedPharmacyIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/upgrade/': typeof ProtectedUpgradeIndexRoute
  '/_protected/outpatient/diagnose/$id': typeof ProtectedOutpatientDiagnoseIdRoute
  '/_protected/outpatient/visit/$id': typeof ProtectedOutpatientVisitIdRoute
  '/_protected/outpatient/visit/create': typeof ProtectedOutpatientVisitCreateRoute
  '/_protected/pharmacy/medicine/$id': typeof ProtectedPharmacyMedicineIdRoute
  '/_protected/pharmacy/medicine/create': typeof ProtectedPharmacyMedicineCreateRoute
  '/_protected/pharmacy/warehouse/$id': typeof ProtectedPharmacyWarehouseIdRoute
  '/_protected/pharmacy/warehouse/create': typeof ProtectedPharmacyWarehouseCreateRoute
  '/_protected/settings/patients/$id': typeof ProtectedSettingsPatientsIdRoute
  '/_protected/settings/patients/create': typeof ProtectedSettingsPatientsCreateRoute
  '/_protected/billing/inpatient/': typeof ProtectedBillingInpatientIndexRoute
  '/_protected/billing/outpatient/': typeof ProtectedBillingOutpatientIndexRoute
  '/_protected/facilities/inpatient/': typeof ProtectedFacilitiesInpatientIndexRoute
  '/_protected/master/module/': typeof ProtectedMasterModuleIndexRoute
  '/_protected/outpatient/visit/': typeof ProtectedOutpatientVisitIndexRoute
  '/_protected/settings/medicine-management/': typeof ProtectedSettingsMedicineManagementIndexRoute
  '/_protected/settings/patients/': typeof ProtectedSettingsPatientsIndexRoute
  '/_protected/settings/references/': typeof ProtectedSettingsReferencesIndexRoute
  '/_protected/settings/users-management/': typeof ProtectedSettingsUsersManagementIndexRoute
  '/_protected/outpatient/visit/edit/$id': typeof ProtectedOutpatientVisitEditIdRoute
  '/_protected/pharmacy/medicine/stocks/$id': typeof ProtectedPharmacyMedicineStocksIdRoute
  '/_protected/settings/medicine-management/medicine/$id': typeof ProtectedSettingsMedicineManagementMedicineIdRoute
  '/_protected/settings/medicine-management/medicine/create': typeof ProtectedSettingsMedicineManagementMedicineCreateRoute
  '/_protected/settings/medicine-management/warehouse/$id': typeof ProtectedSettingsMedicineManagementWarehouseIdRoute
  '/_protected/settings/medicine-management/warehouse/create': typeof ProtectedSettingsMedicineManagementWarehouseCreateRoute
  '/_protected/settings/patients/details/$id': typeof ProtectedSettingsPatientsDetailsIdRoute
  '/_protected/settings/users-management/users/create': typeof ProtectedSettingsUsersManagementUsersCreateRoute
  '/_protected/settings/users-management/roles/': typeof ProtectedSettingsUsersManagementRolesIndexRoute
  '/_protected/settings/medicine-management/medicine/stocks/$id': typeof ProtectedSettingsMedicineManagementMedicineStocksIdRoute
  '/_protected/settings/users-management/users/$id/detail': typeof ProtectedSettingsUsersManagementUsersIdDetailRoute
  '/_protected/settings/users-management/users/$id/': typeof ProtectedSettingsUsersManagementUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/email/verify'
    | '/appointments/$id'
    | '/appointments/create'
    | '/inpatient/$id'
    | '/inpatient/create'
    | '/accounting/'
    | '/appointments/'
    | '/electronic-medical-record/'
    | '/facilities/'
    | '/inpatient/'
    | '/outpatient/'
    | '/pharmacy/'
    | '/settings/'
    | '/upgrade/'
    | '/outpatient/diagnose/$id'
    | '/outpatient/visit/$id'
    | '/outpatient/visit/create'
    | '/pharmacy/medicine/$id'
    | '/pharmacy/medicine/create'
    | '/pharmacy/warehouse/$id'
    | '/pharmacy/warehouse/create'
    | '/settings/patients/$id'
    | '/settings/patients/create'
    | '/billing/inpatient/'
    | '/billing/outpatient/'
    | '/facilities/inpatient/'
    | '/master/module/'
    | '/outpatient/visit/'
    | '/settings/medicine-management/'
    | '/settings/patients/'
    | '/settings/references/'
    | '/settings/users-management/'
    | '/outpatient/visit/edit/$id'
    | '/pharmacy/medicine/stocks/$id'
    | '/settings/medicine-management/medicine/$id'
    | '/settings/medicine-management/medicine/create'
    | '/settings/medicine-management/warehouse/$id'
    | '/settings/medicine-management/warehouse/create'
    | '/settings/patients/details/$id'
    | '/settings/users-management/users/create'
    | '/settings/users-management/roles/'
    | '/settings/medicine-management/medicine/stocks/$id'
    | '/settings/users-management/users/$id/detail'
    | '/settings/users-management/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/email/verify'
    | '/appointments/$id'
    | '/appointments/create'
    | '/inpatient/$id'
    | '/inpatient/create'
    | '/accounting'
    | '/appointments'
    | '/electronic-medical-record'
    | '/facilities'
    | '/inpatient'
    | '/outpatient'
    | '/pharmacy'
    | '/settings'
    | '/upgrade'
    | '/outpatient/diagnose/$id'
    | '/outpatient/visit/$id'
    | '/outpatient/visit/create'
    | '/pharmacy/medicine/$id'
    | '/pharmacy/medicine/create'
    | '/pharmacy/warehouse/$id'
    | '/pharmacy/warehouse/create'
    | '/settings/patients/$id'
    | '/settings/patients/create'
    | '/billing/inpatient'
    | '/billing/outpatient'
    | '/facilities/inpatient'
    | '/master/module'
    | '/outpatient/visit'
    | '/settings/medicine-management'
    | '/settings/patients'
    | '/settings/references'
    | '/settings/users-management'
    | '/outpatient/visit/edit/$id'
    | '/pharmacy/medicine/stocks/$id'
    | '/settings/medicine-management/medicine/$id'
    | '/settings/medicine-management/medicine/create'
    | '/settings/medicine-management/warehouse/$id'
    | '/settings/medicine-management/warehouse/create'
    | '/settings/patients/details/$id'
    | '/settings/users-management/users/create'
    | '/settings/users-management/roles'
    | '/settings/medicine-management/medicine/stocks/$id'
    | '/settings/users-management/users/$id/detail'
    | '/settings/users-management/users/$id'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_protected'
    | '/_protected/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/email/verify'
    | '/_protected/appointments/$id'
    | '/_protected/appointments/create'
    | '/_protected/inpatient/$id'
    | '/_protected/inpatient/create'
    | '/_protected/accounting/'
    | '/_protected/appointments/'
    | '/_protected/electronic-medical-record/'
    | '/_protected/facilities/'
    | '/_protected/inpatient/'
    | '/_protected/outpatient/'
    | '/_protected/pharmacy/'
    | '/_protected/settings/'
    | '/_protected/upgrade/'
    | '/_protected/outpatient/diagnose/$id'
    | '/_protected/outpatient/visit/$id'
    | '/_protected/outpatient/visit/create'
    | '/_protected/pharmacy/medicine/$id'
    | '/_protected/pharmacy/medicine/create'
    | '/_protected/pharmacy/warehouse/$id'
    | '/_protected/pharmacy/warehouse/create'
    | '/_protected/settings/patients/$id'
    | '/_protected/settings/patients/create'
    | '/_protected/billing/inpatient/'
    | '/_protected/billing/outpatient/'
    | '/_protected/facilities/inpatient/'
    | '/_protected/master/module/'
    | '/_protected/outpatient/visit/'
    | '/_protected/settings/medicine-management/'
    | '/_protected/settings/patients/'
    | '/_protected/settings/references/'
    | '/_protected/settings/users-management/'
    | '/_protected/outpatient/visit/edit/$id'
    | '/_protected/pharmacy/medicine/stocks/$id'
    | '/_protected/settings/medicine-management/medicine/$id'
    | '/_protected/settings/medicine-management/medicine/create'
    | '/_protected/settings/medicine-management/warehouse/$id'
    | '/_protected/settings/medicine-management/warehouse/create'
    | '/_protected/settings/patients/details/$id'
    | '/_protected/settings/users-management/users/create'
    | '/_protected/settings/users-management/roles/'
    | '/_protected/settings/medicine-management/medicine/stocks/$id'
    | '/_protected/settings/users-management/users/$id/detail'
    | '/_protected/settings/users-management/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  EmailVerifyRoute: typeof EmailVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/verify': {
      id: '/email/verify'
      path: '/email/verify'
      fullPath: '/email/verify'
      preLoaderRoute: typeof EmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/upgrade/': {
      id: '/_protected/upgrade/'
      path: '/upgrade'
      fullPath: '/upgrade/'
      preLoaderRoute: typeof ProtectedUpgradeIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pharmacy/': {
      id: '/_protected/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof ProtectedPharmacyIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/outpatient/': {
      id: '/_protected/outpatient/'
      path: '/outpatient'
      fullPath: '/outpatient/'
      preLoaderRoute: typeof ProtectedOutpatientIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inpatient/': {
      id: '/_protected/inpatient/'
      path: '/inpatient'
      fullPath: '/inpatient/'
      preLoaderRoute: typeof ProtectedInpatientIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/facilities/': {
      id: '/_protected/facilities/'
      path: '/facilities'
      fullPath: '/facilities/'
      preLoaderRoute: typeof ProtectedFacilitiesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/electronic-medical-record/': {
      id: '/_protected/electronic-medical-record/'
      path: '/electronic-medical-record'
      fullPath: '/electronic-medical-record/'
      preLoaderRoute: typeof ProtectedElectronicMedicalRecordIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/appointments/': {
      id: '/_protected/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof ProtectedAppointmentsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/accounting/': {
      id: '/_protected/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof ProtectedAccountingIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inpatient/create': {
      id: '/_protected/inpatient/create'
      path: '/inpatient/create'
      fullPath: '/inpatient/create'
      preLoaderRoute: typeof ProtectedInpatientCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inpatient/$id': {
      id: '/_protected/inpatient/$id'
      path: '/inpatient/$id'
      fullPath: '/inpatient/$id'
      preLoaderRoute: typeof ProtectedInpatientIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/appointments/create': {
      id: '/_protected/appointments/create'
      path: '/appointments/create'
      fullPath: '/appointments/create'
      preLoaderRoute: typeof ProtectedAppointmentsCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/appointments/$id': {
      id: '/_protected/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof ProtectedAppointmentsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/users-management/': {
      id: '/_protected/settings/users-management/'
      path: '/settings/users-management'
      fullPath: '/settings/users-management/'
      preLoaderRoute: typeof ProtectedSettingsUsersManagementIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/references/': {
      id: '/_protected/settings/references/'
      path: '/settings/references'
      fullPath: '/settings/references/'
      preLoaderRoute: typeof ProtectedSettingsReferencesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/patients/': {
      id: '/_protected/settings/patients/'
      path: '/settings/patients'
      fullPath: '/settings/patients/'
      preLoaderRoute: typeof ProtectedSettingsPatientsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/medicine-management/': {
      id: '/_protected/settings/medicine-management/'
      path: '/settings/medicine-management'
      fullPath: '/settings/medicine-management/'
      preLoaderRoute: typeof ProtectedSettingsMedicineManagementIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/outpatient/visit/': {
      id: '/_protected/outpatient/visit/'
      path: '/outpatient/visit'
      fullPath: '/outpatient/visit/'
      preLoaderRoute: typeof ProtectedOutpatientVisitIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/master/module/': {
      id: '/_protected/master/module/'
      path: '/master/module'
      fullPath: '/master/module/'
      preLoaderRoute: typeof ProtectedMasterModuleIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/facilities/inpatient/': {
      id: '/_protected/facilities/inpatient/'
      path: '/facilities/inpatient'
      fullPath: '/facilities/inpatient/'
      preLoaderRoute: typeof ProtectedFacilitiesInpatientIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/billing/outpatient/': {
      id: '/_protected/billing/outpatient/'
      path: '/billing/outpatient'
      fullPath: '/billing/outpatient/'
      preLoaderRoute: typeof ProtectedBillingOutpatientIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/billing/inpatient/': {
      id: '/_protected/billing/inpatient/'
      path: '/billing/inpatient'
      fullPath: '/billing/inpatient/'
      preLoaderRoute: typeof ProtectedBillingInpatientIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/patients/create': {
      id: '/_protected/settings/patients/create'
      path: '/settings/patients/create'
      fullPath: '/settings/patients/create'
      preLoaderRoute: typeof ProtectedSettingsPatientsCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/patients/$id': {
      id: '/_protected/settings/patients/$id'
      path: '/settings/patients/$id'
      fullPath: '/settings/patients/$id'
      preLoaderRoute: typeof ProtectedSettingsPatientsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pharmacy/warehouse/create': {
      id: '/_protected/pharmacy/warehouse/create'
      path: '/pharmacy/warehouse/create'
      fullPath: '/pharmacy/warehouse/create'
      preLoaderRoute: typeof ProtectedPharmacyWarehouseCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pharmacy/warehouse/$id': {
      id: '/_protected/pharmacy/warehouse/$id'
      path: '/pharmacy/warehouse/$id'
      fullPath: '/pharmacy/warehouse/$id'
      preLoaderRoute: typeof ProtectedPharmacyWarehouseIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pharmacy/medicine/create': {
      id: '/_protected/pharmacy/medicine/create'
      path: '/pharmacy/medicine/create'
      fullPath: '/pharmacy/medicine/create'
      preLoaderRoute: typeof ProtectedPharmacyMedicineCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pharmacy/medicine/$id': {
      id: '/_protected/pharmacy/medicine/$id'
      path: '/pharmacy/medicine/$id'
      fullPath: '/pharmacy/medicine/$id'
      preLoaderRoute: typeof ProtectedPharmacyMedicineIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/outpatient/visit/create': {
      id: '/_protected/outpatient/visit/create'
      path: '/outpatient/visit/create'
      fullPath: '/outpatient/visit/create'
      preLoaderRoute: typeof ProtectedOutpatientVisitCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/outpatient/visit/$id': {
      id: '/_protected/outpatient/visit/$id'
      path: '/outpatient/visit/$id'
      fullPath: '/outpatient/visit/$id'
      preLoaderRoute: typeof ProtectedOutpatientVisitIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/outpatient/diagnose/$id': {
      id: '/_protected/outpatient/diagnose/$id'
      path: '/outpatient/diagnose/$id'
      fullPath: '/outpatient/diagnose/$id'
      preLoaderRoute: typeof ProtectedOutpatientDiagnoseIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/users-management/roles/': {
      id: '/_protected/settings/users-management/roles/'
      path: '/settings/users-management/roles'
      fullPath: '/settings/users-management/roles/'
      preLoaderRoute: typeof ProtectedSettingsUsersManagementRolesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/users-management/users/create': {
      id: '/_protected/settings/users-management/users/create'
      path: '/settings/users-management/users/create'
      fullPath: '/settings/users-management/users/create'
      preLoaderRoute: typeof ProtectedSettingsUsersManagementUsersCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/patients/details/$id': {
      id: '/_protected/settings/patients/details/$id'
      path: '/settings/patients/details/$id'
      fullPath: '/settings/patients/details/$id'
      preLoaderRoute: typeof ProtectedSettingsPatientsDetailsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/medicine-management/warehouse/create': {
      id: '/_protected/settings/medicine-management/warehouse/create'
      path: '/settings/medicine-management/warehouse/create'
      fullPath: '/settings/medicine-management/warehouse/create'
      preLoaderRoute: typeof ProtectedSettingsMedicineManagementWarehouseCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/medicine-management/warehouse/$id': {
      id: '/_protected/settings/medicine-management/warehouse/$id'
      path: '/settings/medicine-management/warehouse/$id'
      fullPath: '/settings/medicine-management/warehouse/$id'
      preLoaderRoute: typeof ProtectedSettingsMedicineManagementWarehouseIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/medicine-management/medicine/create': {
      id: '/_protected/settings/medicine-management/medicine/create'
      path: '/settings/medicine-management/medicine/create'
      fullPath: '/settings/medicine-management/medicine/create'
      preLoaderRoute: typeof ProtectedSettingsMedicineManagementMedicineCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/medicine-management/medicine/$id': {
      id: '/_protected/settings/medicine-management/medicine/$id'
      path: '/settings/medicine-management/medicine/$id'
      fullPath: '/settings/medicine-management/medicine/$id'
      preLoaderRoute: typeof ProtectedSettingsMedicineManagementMedicineIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pharmacy/medicine/stocks/$id': {
      id: '/_protected/pharmacy/medicine/stocks/$id'
      path: '/pharmacy/medicine/stocks/$id'
      fullPath: '/pharmacy/medicine/stocks/$id'
      preLoaderRoute: typeof ProtectedPharmacyMedicineStocksIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/outpatient/visit/edit/$id': {
      id: '/_protected/outpatient/visit/edit/$id'
      path: '/outpatient/visit/edit/$id'
      fullPath: '/outpatient/visit/edit/$id'
      preLoaderRoute: typeof ProtectedOutpatientVisitEditIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/users-management/users/$id/': {
      id: '/_protected/settings/users-management/users/$id/'
      path: '/settings/users-management/users/$id'
      fullPath: '/settings/users-management/users/$id/'
      preLoaderRoute: typeof ProtectedSettingsUsersManagementUsersIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/users-management/users/$id/detail': {
      id: '/_protected/settings/users-management/users/$id/detail'
      path: '/settings/users-management/users/$id/detail'
      fullPath: '/settings/users-management/users/$id/detail'
      preLoaderRoute: typeof ProtectedSettingsUsersManagementUsersIdDetailRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/medicine-management/medicine/stocks/$id': {
      id: '/_protected/settings/medicine-management/medicine/stocks/$id'
      path: '/settings/medicine-management/medicine/stocks/$id'
      fullPath: '/settings/medicine-management/medicine/stocks/$id'
      preLoaderRoute: typeof ProtectedSettingsMedicineManagementMedicineStocksIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedAppointmentsIdRoute: typeof ProtectedAppointmentsIdRoute
  ProtectedAppointmentsCreateRoute: typeof ProtectedAppointmentsCreateRoute
  ProtectedInpatientIdRoute: typeof ProtectedInpatientIdRoute
  ProtectedInpatientCreateRoute: typeof ProtectedInpatientCreateRoute
  ProtectedAccountingIndexRoute: typeof ProtectedAccountingIndexRoute
  ProtectedAppointmentsIndexRoute: typeof ProtectedAppointmentsIndexRoute
  ProtectedElectronicMedicalRecordIndexRoute: typeof ProtectedElectronicMedicalRecordIndexRoute
  ProtectedFacilitiesIndexRoute: typeof ProtectedFacilitiesIndexRoute
  ProtectedInpatientIndexRoute: typeof ProtectedInpatientIndexRoute
  ProtectedOutpatientIndexRoute: typeof ProtectedOutpatientIndexRoute
  ProtectedPharmacyIndexRoute: typeof ProtectedPharmacyIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedUpgradeIndexRoute: typeof ProtectedUpgradeIndexRoute
  ProtectedOutpatientDiagnoseIdRoute: typeof ProtectedOutpatientDiagnoseIdRoute
  ProtectedOutpatientVisitIdRoute: typeof ProtectedOutpatientVisitIdRoute
  ProtectedOutpatientVisitCreateRoute: typeof ProtectedOutpatientVisitCreateRoute
  ProtectedPharmacyMedicineIdRoute: typeof ProtectedPharmacyMedicineIdRoute
  ProtectedPharmacyMedicineCreateRoute: typeof ProtectedPharmacyMedicineCreateRoute
  ProtectedPharmacyWarehouseIdRoute: typeof ProtectedPharmacyWarehouseIdRoute
  ProtectedPharmacyWarehouseCreateRoute: typeof ProtectedPharmacyWarehouseCreateRoute
  ProtectedSettingsPatientsIdRoute: typeof ProtectedSettingsPatientsIdRoute
  ProtectedSettingsPatientsCreateRoute: typeof ProtectedSettingsPatientsCreateRoute
  ProtectedBillingInpatientIndexRoute: typeof ProtectedBillingInpatientIndexRoute
  ProtectedBillingOutpatientIndexRoute: typeof ProtectedBillingOutpatientIndexRoute
  ProtectedFacilitiesInpatientIndexRoute: typeof ProtectedFacilitiesInpatientIndexRoute
  ProtectedMasterModuleIndexRoute: typeof ProtectedMasterModuleIndexRoute
  ProtectedOutpatientVisitIndexRoute: typeof ProtectedOutpatientVisitIndexRoute
  ProtectedSettingsMedicineManagementIndexRoute: typeof ProtectedSettingsMedicineManagementIndexRoute
  ProtectedSettingsPatientsIndexRoute: typeof ProtectedSettingsPatientsIndexRoute
  ProtectedSettingsReferencesIndexRoute: typeof ProtectedSettingsReferencesIndexRoute
  ProtectedSettingsUsersManagementIndexRoute: typeof ProtectedSettingsUsersManagementIndexRoute
  ProtectedOutpatientVisitEditIdRoute: typeof ProtectedOutpatientVisitEditIdRoute
  ProtectedPharmacyMedicineStocksIdRoute: typeof ProtectedPharmacyMedicineStocksIdRoute
  ProtectedSettingsMedicineManagementMedicineIdRoute: typeof ProtectedSettingsMedicineManagementMedicineIdRoute
  ProtectedSettingsMedicineManagementMedicineCreateRoute: typeof ProtectedSettingsMedicineManagementMedicineCreateRoute
  ProtectedSettingsMedicineManagementWarehouseIdRoute: typeof ProtectedSettingsMedicineManagementWarehouseIdRoute
  ProtectedSettingsMedicineManagementWarehouseCreateRoute: typeof ProtectedSettingsMedicineManagementWarehouseCreateRoute
  ProtectedSettingsPatientsDetailsIdRoute: typeof ProtectedSettingsPatientsDetailsIdRoute
  ProtectedSettingsUsersManagementUsersCreateRoute: typeof ProtectedSettingsUsersManagementUsersCreateRoute
  ProtectedSettingsUsersManagementRolesIndexRoute: typeof ProtectedSettingsUsersManagementRolesIndexRoute
  ProtectedSettingsMedicineManagementMedicineStocksIdRoute: typeof ProtectedSettingsMedicineManagementMedicineStocksIdRoute
  ProtectedSettingsUsersManagementUsersIdDetailRoute: typeof ProtectedSettingsUsersManagementUsersIdDetailRoute
  ProtectedSettingsUsersManagementUsersIdIndexRoute: typeof ProtectedSettingsUsersManagementUsersIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedAppointmentsIdRoute: ProtectedAppointmentsIdRoute,
  ProtectedAppointmentsCreateRoute: ProtectedAppointmentsCreateRoute,
  ProtectedInpatientIdRoute: ProtectedInpatientIdRoute,
  ProtectedInpatientCreateRoute: ProtectedInpatientCreateRoute,
  ProtectedAccountingIndexRoute: ProtectedAccountingIndexRoute,
  ProtectedAppointmentsIndexRoute: ProtectedAppointmentsIndexRoute,
  ProtectedElectronicMedicalRecordIndexRoute:
    ProtectedElectronicMedicalRecordIndexRoute,
  ProtectedFacilitiesIndexRoute: ProtectedFacilitiesIndexRoute,
  ProtectedInpatientIndexRoute: ProtectedInpatientIndexRoute,
  ProtectedOutpatientIndexRoute: ProtectedOutpatientIndexRoute,
  ProtectedPharmacyIndexRoute: ProtectedPharmacyIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedUpgradeIndexRoute: ProtectedUpgradeIndexRoute,
  ProtectedOutpatientDiagnoseIdRoute: ProtectedOutpatientDiagnoseIdRoute,
  ProtectedOutpatientVisitIdRoute: ProtectedOutpatientVisitIdRoute,
  ProtectedOutpatientVisitCreateRoute: ProtectedOutpatientVisitCreateRoute,
  ProtectedPharmacyMedicineIdRoute: ProtectedPharmacyMedicineIdRoute,
  ProtectedPharmacyMedicineCreateRoute: ProtectedPharmacyMedicineCreateRoute,
  ProtectedPharmacyWarehouseIdRoute: ProtectedPharmacyWarehouseIdRoute,
  ProtectedPharmacyWarehouseCreateRoute: ProtectedPharmacyWarehouseCreateRoute,
  ProtectedSettingsPatientsIdRoute: ProtectedSettingsPatientsIdRoute,
  ProtectedSettingsPatientsCreateRoute: ProtectedSettingsPatientsCreateRoute,
  ProtectedBillingInpatientIndexRoute: ProtectedBillingInpatientIndexRoute,
  ProtectedBillingOutpatientIndexRoute: ProtectedBillingOutpatientIndexRoute,
  ProtectedFacilitiesInpatientIndexRoute:
    ProtectedFacilitiesInpatientIndexRoute,
  ProtectedMasterModuleIndexRoute: ProtectedMasterModuleIndexRoute,
  ProtectedOutpatientVisitIndexRoute: ProtectedOutpatientVisitIndexRoute,
  ProtectedSettingsMedicineManagementIndexRoute:
    ProtectedSettingsMedicineManagementIndexRoute,
  ProtectedSettingsPatientsIndexRoute: ProtectedSettingsPatientsIndexRoute,
  ProtectedSettingsReferencesIndexRoute: ProtectedSettingsReferencesIndexRoute,
  ProtectedSettingsUsersManagementIndexRoute:
    ProtectedSettingsUsersManagementIndexRoute,
  ProtectedOutpatientVisitEditIdRoute: ProtectedOutpatientVisitEditIdRoute,
  ProtectedPharmacyMedicineStocksIdRoute:
    ProtectedPharmacyMedicineStocksIdRoute,
  ProtectedSettingsMedicineManagementMedicineIdRoute:
    ProtectedSettingsMedicineManagementMedicineIdRoute,
  ProtectedSettingsMedicineManagementMedicineCreateRoute:
    ProtectedSettingsMedicineManagementMedicineCreateRoute,
  ProtectedSettingsMedicineManagementWarehouseIdRoute:
    ProtectedSettingsMedicineManagementWarehouseIdRoute,
  ProtectedSettingsMedicineManagementWarehouseCreateRoute:
    ProtectedSettingsMedicineManagementWarehouseCreateRoute,
  ProtectedSettingsPatientsDetailsIdRoute:
    ProtectedSettingsPatientsDetailsIdRoute,
  ProtectedSettingsUsersManagementUsersCreateRoute:
    ProtectedSettingsUsersManagementUsersCreateRoute,
  ProtectedSettingsUsersManagementRolesIndexRoute:
    ProtectedSettingsUsersManagementRolesIndexRoute,
  ProtectedSettingsMedicineManagementMedicineStocksIdRoute:
    ProtectedSettingsMedicineManagementMedicineStocksIdRoute,
  ProtectedSettingsUsersManagementUsersIdDetailRoute:
    ProtectedSettingsUsersManagementUsersIdDetailRoute,
  ProtectedSettingsUsersManagementUsersIdIndexRoute:
    ProtectedSettingsUsersManagementUsersIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  EmailVerifyRoute: EmailVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
