export const plans = [
    {
        id: 'free',
        title: 'Free',
        description: 'Untuk mencoba fitur dasar sistem klinik.',
        currency: 'Rp',
        monthlyPrice: '0',
        yearlyPrice: '0',
        buttonText: 'Mulai Gratis',
        features: [
            {name: 'Dashboard', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Rawat Jalan', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Antrian Pasien', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Maks. 3 pengguna', icon: 'check', iconColor: 'text-zinc-500'},
            {name: 'Rawat Inap', icon: 'x', iconColor: 'text-red-400'},
            {name: 'Farmasi & Obat', icon: 'x', iconColor: 'text-red-400'},
            {name: 'EMR', icon: 'x', iconColor: 'text-red-400'},
            {name: 'Akuntansi', icon: 'x', iconColor: 'text-red-400'},
        ],
    },
    {
        id: 'basic',
        title: 'Basic',
        description: 'Untuk klinik kecil dengan kebutuhan rawat jalan dan rawat inap.',
        currency: 'Rp',
        monthlyPrice: '99.000',
        yearlyPrice: '990.000',
        buttonText: 'Pilih Basic',
        badge: 'Populer',
        highlight: false,
        features: [
            {name: 'Semua fitur Free', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Rawat Inap', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Fasilitas (Gedung, Ruang, Bed)', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Master Data', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Maks. 5 pengguna', icon: 'check', iconColor: 'text-zinc-500'},
            {name: 'Farmasi & Obat', icon: 'x', iconColor: 'text-red-400'},
            {name: 'EMR', icon: 'x', iconColor: 'text-red-400'},
            {name: 'Akuntansi', icon: 'x', iconColor: 'text-red-400'},
        ],
    },
    {
        id: 'pro',
        title: 'Pro',
        description: 'Paket lengkap untuk klinik dengan kebutuhan penuh.',
        currency: 'Rp',
        monthlyPrice: '199.000',
        yearlyPrice: '1.990.000',
        buttonText: 'Pilih Pro',
        badge: 'Terlengkap',
        highlight: true,
        features: [
            {name: 'Semua fitur Basic', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Farmasi & Obat', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Electronic Medical Record (EMR)', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Akuntansi', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Resep Digital', icon: 'check', iconColor: 'text-green-500'},
            {name: 'Pengguna unlimited', icon: 'check', iconColor: 'text-green-500'},
        ],
    },
];